### Conda (environment.yml)
name: urbanair312v1

channels:
 - conda-forge

dependencies:
 - python=3.12
 - ipython
 - ipykernel
 ##### IDE
 - jupyter
 - jupyterlab
##### Data Science:
 - numpy
 - xarray
 - pandas
 - scipy
 ##### IO, files, formats, APIs, Viz:
 - plotly
 - python-kaleido
 - mergedeep
 - humanize
 - cftime
 - cfgrib
 - cfunits
 - udunits2
 - zarr=<3.0  
 - netCDF4
 - fsspec
 - numcodecs
 - bottleneck
 - numbagg
 - dask
 - fiona
 ##### PIP
 - pip
 - pip:
    - zenodo-get    